ecomers/myproj/authentication/urls.py
from django.urls import path, include
from . import views

app_name  = 'authentication'

urlpatterns = [
   
    path('', views.index , name='index'),
    path('signup/', views.signup , name='signup'),
    path('login/', views.login , name='login'),
    path('logout/', views.logout , name='logout'),
]

ecomers/myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls'))
]

ecomers/myproj/authentication/models.py
from django.db import models

# Create your models here.

ecomers/myproj/authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import auth,messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import authenticate, login as auth_login



def index(request):
    return render (request, "index.html")


def signup(request):
    if request.method == 'POST':
        u_name = request.POST.get('username') 
        mail = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        
        if u_name and mail and pass1 and pass2:
            if pass1 == pass2:
                if User.objects.filter(username=u_name).exists(): 
                    messages.error(request, "the username already exist" )
                    return redirect('authentication:signup')
                else:
                    user = User.objects.create_user(username=u_name, email=mail, password=pass1)
                    user.save()
                    return redirect('authentication:login')
            else:
                messages.error(request, "doesn't match password" )
                return redirect('authentication:signup')
        else:
            return redirect('authentication:signup')
    else:                
        return render(request, "signup.html")




from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login

def login(request):
    if request.method == 'POST':
        u_name = request.POST.get('username')
        pass1 = request.POST.get('password')
        
        user = authenticate(request, username=u_name, password=pass1)
        
        if user is not None:
            auth_login(request, user)
            return redirect('authentication:index')
        else:
            messages.error(request, 'invalid username or password')
            return redirect('authentication:login')
        
    else:
        return render(request, "login.html")




def logout(request):
    auth.logout(request)
    return redirect('authentication:index')

ecomers/myproj/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    {% block link %}{% endblock link %}

  </head>
  <body>
    {% include "navbar.html" %}
    {% block content %}{% endblock content %}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}

  </body>
</html>

ecomers/myproj/templates/index.html
{% extends "base.html" %}
{% load static %}

    {% block link %}{% endblock link %}



    {% block content %}
    
    <div class="container mt-5">

        
        
          <br><br><br>
        </div>
        <div class="container mt-4">
          <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
            <div class="col ">
              <div class="card  text-center border-secondary border-2  "style="height: 480px;">
                <img src="5323fb4b-942d-4827-add0-de0a8373b04a.jpeg"  alt="taj" class="card-img-top" style="height: 250px;" >
                <div class="card-body ">
                  <h5 class="card-title">Taj Mahal</h5>
                  <p>Taj Mahal: Stunning white marble mausoleum in Agra, India, built by Mughal Emperor Shah Jahan in 1653, a UNESCO World Heritage Site and symbol of eternal love.</p>
                </div>
              </div>
            </div>
        
            <div class="col">
              <div class="card text-center border-secondary border-2 " style="height: 480px;">
                <img src="13c10e94-a4f0-4c0a-b3c1-b6b86e60e4e2.jpeg" alt="taj" class="card-img-top" style="height: 250px;">
                <div class="card-body  ">
                  <h5 class="card-title ">Qutb Minar</h5>
                  <p class="mb-3">Qutub Minar: Tallest Indian minaret, built in 1220, 73m high, red sandstone, Indo-Islamic architecture, UNESCO World Heritage Site, Delhi's iconic historical landmark.</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card text-center border-secondary border-2 "style="height: 480px;">
                <img src="edb90b66-e293-4846-9392-5397a9fe6de0.jpeg" alt="taj" class="card-img-top" style="height: 250px;">
                <div class="card-body  ">
                  <h5 class="card-title ">Charminar</h5>
                  <p class="mb-3">Charminar: Iconic Hyderabad monument, built in 1591, with four minarets, mosque, and Indo-Islamic architecture, symbolizing city's rich history and cultural heritage. </p>
                </div>
              </div>
            </div> 
        
          
        
            <div class="col">
              <div class="card text-center border-secondary border-2 "style="height: 480px;">
                <img src="93e819e5-a4d4-4fac-a200-f75019a4ea80.jpeg" alt="taj" class="card-img-top" style="height: 250px;" >
                <div class="card-body ">
                  <h5 class="card-title ">Red Fort</h5>
                  <p>Red Fort: 17th-century Delhi fortress, built by Shah Jahan, red sandstone, Mughal architecture, UNESCO Site, India's iconic historical monument, palace, and museum complex.</p>
                </div>
              </div>
            </div>
        
            <div class="col">
              <div class="card text-center border-secondary border-2 "style="height: 480px;">
                <img src="25f49ac5-eb06-4bec-9496-21c441a136a6.jpeg" alt="taj"class="card-img-top" style="height: 250px;">
                <div class="card-body ">
                  <h5 class="card-title">Ladak</h5>
                  <p>Ladakh: Scenic Indian region, high-altitude desert, Himalayan landscape, Buddhist monasteries, trekking trails, crystal-clear lakes, and picturesque villages, serene beauty.</p>
                </div>
              </div>
            </div>
        
        
            <div class="col">
              <div class="card text-center border-secondary border-2 " style="height: 480px;">
                <img src="b6bf5d32-fac1-4b7d-8d67-b7807975a81f.jpeg" alt="taj" class="card-img-top" style="height: 250px;" >
                <div class="card-body ">
                  <h5 class="card-title ">Indian Gate</h5>
                  <p>India Gate: Iconic Delhi monument, war memorial, 42m high, red sandstone, honors Indian soldiers, beautiful gardens, evening illuminations, national pride and symbolism.</p>
                </div>
              </div>
            </div>
        
        
            <div class="col">
              <div class="card text-center border-secondary border-2 " style="height: 480px;">
                <img src="fc4ddacc-72a4-4317-ae0f-8572f583da4f.jpeg" alt="taj" class="card-img-top " style="height: 250px;">
                <div class="card-body ">
                  <h5 class="card-title">Jaipur Palac</h5>
                  <p> Jaipur Palace: Majestic Rajasthan palace, blend of Rajput and Mughal architecture, intricate designs, courtyards, gardens, royal grandeur, and rich cultural heritage, stunning beauty.</p>
                </div>
              </div>
            </div>
        
        
            <div class="col">
              <div class="card text-center border-secondary border-2 " style="height: 480px;">
                <img src="6dc930cf-98c6-4d10-9136-da75ecd63ee8.jpeg" alt="taj"class="card-img-top" style="height: 250px;" >
                <div class="card-body ">
                  <h5 class="card-title">Mysure Palace</h5>
                  <p>Mysore Palace: Grand Karnataka palace, Indo-Saracenic architecture, ornate decorations, stained glass, carved wooden doors, majestic halls, and vibrant gardens, royal splendor.  </p>
                </div>
              </div>
            </div>
        
            <footer class="blockquote-footer bg-transparend text-center fs-5">Indian Tourist Places</footer>
        
        
          </div>
        </div>
    
        
        </div>
          
        
        
        
        
        
       



    </div>

    {% endblock content %}



    {% block script %}{% endblock script %}

ecomers/myproj/templates/login.html
{% extends "base.html" %}
{% load static %}

    {% block link %}
    
    <style>
        body{
            background: color #f8f8f8;
        }
        .container{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .card{
            padding: 2rem;
            border-radius: 0.5rem;
            box-shadow: 0 4px 8px rgba(0, 0, 0,0.1);
            width: 25rem;
        }
    </style>

    {% endblock link %}



    {% block content %}
    
    <div class="container">

        <div class="card">
            <h3 class="card-title text-center text-primary" >Login</h3>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group pt-5">
                    <input class="form-control" type="text" name="username" id="username" placeholder="username">
                </div>
            
                <div class="form-group pt-3">              
                    <input class="form-control" type="password" name="password" id="password" placeholder="password">
                </div>
                {% if messages %}

                
                    {% for message in messages %}

                    <small> <p class=" mb-0 text-center text-danger alert alert-{{message.tags}}">{{message}} </p></small>
               {% endfor %}
            
                {% endif %}
                <div class="form-group pt-4 text-center">
                    <input class="btn btn-primary text-center px-5" type="submit">
                </div>

               
                </div>
                
                {% endblock content %}
            </form>
            
        </div>
    </div>
   



    {% block script %}
    {% endblock script %}
    

ecomers/myproj/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
  <div class="container-fluid">
    <a class="navbar-brand h1 px-5 text-light" href="{% url "authentication:index" %}">VN SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-iconvV text-light"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
        <li class="nav-item me-2">
          <a class="nav-link active text-light" aria-current="page" href="{% url "authentication:index" %}">Home</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link text-light" href="#">Profile</a>
        </li>
        
        {% if user.is_authenticated %}
        
        <li class="nav-item me-2">
          <a class="nav-link text-light" href="{% url "authentication:logout" %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item me-2">
          <a class="nav-link text-light " href="{% url "authentication:signup" %}">Signup</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link text-light" href="{% url "authentication:login" %}">Login</a>
        </li>

        {% endif %}
      
      </ul>
    </div>
  </div>
</nav>

ecomers/myproj/templates/signup.html
{% extends "base.html" %}
{% load static %}

    {% block link %}
    
    <style>
        body{
            background: color #f8f8f8;
        }
        .container{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .card{
            padding: 2rem;
            border-radius: 0.5rem;
            box-shadow: 0 4px 8px rgba(0, 0, 0,0.1);
            width: 30rem;
        }
    </style>

    {% endblock link %}



    {% block content %}
    
    <div class="container">

        <div class="card">
            <h3 class="card-title text-center text-primary" >Sign Up</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-group pt-5">
                    <input class="form-control" type="text" name="username" id="username" placeholder="username">
                </div>
                <div class="form-group pt-3">
                    <input class="form-control" type="email" name="email" id="email" placeholder="email">
                </div>
                <div class="form-group pt-3">              
                    <input class="form-control" type="password" name="password1" id="password1" placeholder="password">
                </div>
                <div class="form-group pt-3">
                    <input class="form-control" type="password" name="password2" id="password2" placeholder="confirm password">
                </div>
                {% if messages %}

                
                {% for message in messages %}

                <small> <p class=" mb-0 text-center text-danger alert alert-{{message.tags}}">{{message}} </p></small>
           {% endfor %}
        
            {% endif %}
                <div class="form-group pt-5 text-center">
                    <input class="btn btn-primary text-center px-5" type="submit">
                </div>
            </form>
            
        </div>
    </div>
    
    {% endblock content %}



    {% block script %}{% endblock script %}
    